### ISSUE TITLE
Loss shoots to NAN within a few iteration

### ISSUE THREAD

**Issue by kannadaraj** [CookiePPP/pag-tacotron2#1]
@CookiePPP 
Thanks a ton for providing the repo. Its great. I pre generated forced alignment and used for training. my trainsi encounters NAN as soon as it starts in a few interations and never recover. .Do you have what might be causing this?
Thanks a lot for any help.
 
![image](https://user-images.githubusercontent.com/17844576/86086601-f181f080-ba56-11ea-8214-7bf18229aed2.png)

**Comment by CookiePPP** [comment]
@kannadaraj 
Not sure.
I'll check over it in a couple of days.

**Comment by kannadaraj** [comment]
@CookiePPP  Thanks a lot for such soon reply. I really appreciate it. take your time. Thanks.. Just to help a bit.. Both attention_weights and attention_context will go NaN after 3 iterations..

![image](https://user-images.githubusercontent.com/17844576/86087158-5a1d9d00-ba58-11ea-9880-64897e09e449.png)


![image](https://user-images.githubusercontent.com/17844576/86087506-39a21280-ba59-11ea-8092-617c23db024d.png)

**Comment by kannadaraj** [comment]
Hi @CookiePPP .. i think its a false alarm..  sry..  After going in-depth to debug; i found that for some strange reason one value in "ONE" generated alignment was had a NaN value which was creating a cascading effect.. I ensured that there is no issues with generated alignments. .Now the training is in progress.. Will keep posted..

**Comment by kannadaraj** [comment]
I will close this issue as the training is in progress.. Thanks..
